version: "3.5"

volumes:
  mongo-data:

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    logging:
      driver: "none"

  app:
    build: .
    command: ['npm', "start", "--silent"] 
    depends_on:
      - mongodb